// Resources
type Resource = {
  name: string
  authors: (keyof typeof People)[]
  description: string | React.ReactNode
  href: string
  type: ResourceType
  conceptTags?: any
}

enum ResourceType {
  book = "book",
  video = "video",
  paper = "paper",
  article = "article",
  podcast = "podcast",
}

export const Resources: Resource[] = [
  {
    name: "The Beginning of Infinity: Explanations That Transform the World",
    authors: ["David Deutsch"],
    description:
      "This is a book by a noted quantum physicist discussing epistemology, the nature of reality, and human progress.",
    href: "https://en.wikipedia.org/wiki/The_Beginning_of_Infinity",
    type: ResourceType.book,
    conceptTags: ["Epistemology and Science"],
  },
  {
    name: "The Logic of Scientific Discovery",
    authors: ["Karl Popper"],
    description:
      "This is a book by a noted philosopher discussing the nature of scientific discovery.",
    href: "https://en.wikipedia.org/wiki/The_Logic_of_Scientific_Discovery",
    type: ResourceType.book,
  },
  {
    name: "Failure: Why Science Is So Successful",
    authors: ["Stuart Firestein"],
    description:
      "This book delves into the origins of scientific research as a process that relies upon trial and error, one which inevitably results in a hefty dose of failure.",
    href: "https://www.goodreads.com/en/book/show/25972391",
    type: ResourceType.book,
  },
  {
    name: "RSA Replay: Optimism, Knowledge and the Future of Enlightenment",
    authors: ["David Deutsch"],
    href: "https://www.youtube.com/watch?v=ncJQTYc27ME&t=0s",
    type: ResourceType.video,
    description:
      "Physicist David Deutsch and cosmologist Martin Rees lead a special event exploring the theme of optimism as a force for 21st century progress.",
  },
  {
    name: "DeutschCap",
    authors: ["David Deutsch", "Aniket Vartak"],
    href: "http://www.aniketvartak.com/html/deutsch-index.html",
    type: ResourceType.video,
    description:
      "Aniket Vartak has created a video index with transcripts generated by OpenAI's Whisper of David Deutsch's talks and interviews.",
  },
  {
    href: "https://arxiv.org/abs/2012.09318",
    name: "Applying Deutsch's concept of good explanations to artificial intelligence and neuroscience -- an initial exploration",
    authors: ["Daniel C. Elton"],
    type: ResourceType.paper,
    description:
      "Investigation of Deutsch's hard-to-vary principle and how it relates to more formalized principles in deep learning such as the bias-variance trade-off and Occam's razor.",
  },
  {
    href: "https://www.youtube.com/watch?v=RoneOk5yI18",
    name: "Liberty Loves Reason: Darwin versus Political Correctness",
    authors: [
      "David Deutsch",
      "Lulie Tanett",
      "Ray Scott Percival",
      // "Edward Crumblehulme", could not find anything about this person
    ],
    type: ResourceType.video,
    description:
      "Documentary inspired by the book The Myth of the Closed Mind.",
  },
  {
    name: "The Myth of the Closed Mind: Understanding Why and How People Are Rational",
    authors: ["Ray Scott Percival"],
    description:
      "Ray Scott Percival sets out to demolish the whole notion of the closed mind and human irrationality",
    href: "https://www.goodreads.com/en/book/show/13235385",
    type: ResourceType.book,
  },
  {
    name: "David Deutsch Eats Rationalism",
    authors: ["Cam Peters"],
    href: "https://falliblepieces.substack.com/p/david-deutsch-eats-rationalism",
    type: ResourceType.article,
    description:
      "Differences of Bayesian Rationality and Critical Rationalism.",
  },
  {
    href: "https://nav.al/infinity",
    name: "The Beginning of Infinity, Part 1",
    authors: ["Naval Ravikant"],
    type: ResourceType.podcast,
    description: "Conversation between Naval Ravikant and Brett Hall.",
  },
  {
    href: "https://www.youtube.com/watch?v=OJHeJmperPw",
    name: "Moral problems: a Popperian approach",
    authors: ["Oliver Scott Curry"],
    type: ResourceType.video,
    description:
      "What is morality? And how ought you behave? These questions, until recently exclusively philosophical, are now becoming scientific.",
  },
  {
    name: "Aaron Stupple's Twitter List of Critical Rationalists",
    authors: ["Aaron Stupple"],
    href: "https://twitter.com/i/lists/1117954597329543174",
    type: ResourceType.article,
    description: "A list of critical rationalists on Twitter by Aaron Stupple",
  },
  {
    name: "Bart Vanderhaegen's Four Strands Twitter list",
    authors: ["Bart Vanderhaegen"],
    href: "https://twitter.com/i/lists/1246825768644206592",
    type: ResourceType.article,
    description:
      "A list of critical rationalists and related profiles on Twitter by Bart Vanderhaegen",
  },
]

// People

type PeopleTypes = {
  name: string
  description: string
  websiteURL?: string
  twitterURL?: string
  died?: string
}

export const People = {
  "David Deutsch": {
    name: "David Deutsch",
    description:
      "David Elieser Deutsch FRS is a British physicist at the University of Oxford. He is a Visiting Professor in the Department of Atomic and Laser Physics at the Centre for Quantum Computation in the Clarendon Laboratory of the University of Oxford.",
    websiteURL: "http://www.daviddeutsch.org.uk/h",
    twitterURL: "https://twitter.com/DavidDeutschOxf",
  } as PeopleTypes,
  "Karl Popper": {
    name: "Karl Popper",
    description:
      "Karl Raimund Popper was an Austrian-British philosopher and professor. He is generally regarded as one of the 20th century's greatest philosophers of science.",
    websiteURL: "https://en.wikipedia.org/wiki/Karl_Popper",
    died: "1994-09-17",
  } as PeopleTypes,
  "Brett Hall": {
    name: "Brett Hall",
    description:
      "Brett Hall is based in Australia and the creator of ToKCast, a podcast largely about the work of David Deutsch.",
    websiteURL: "https://www.bretthall.org/",
    twitterURL: "https://twitter.com/tokteacher/",
  } as PeopleTypes,
  "Peter Medawar": {
    name: "Peter Medawar",
    description:
      "Peter Brian Medawar FRS was a British immunologist and Nobel laureate. He was a professor at the University of Oxford and a Fellow of All Souls College, Oxford.",
    websiteURL: "https://en.wikipedia.org/wiki/Peter_Medawar",
    died: "1987-11-02",
  } as PeopleTypes,
  "Naval Ravikant": {
    name: "Naval Ravikant",
    description:
      "Naval Ravikant is an Indian-American entrepreneur, investor, and author. He is the co-founder and CEO of AngelList and Spearhead",
    websiteURL: "https://nav.al/",
    twitterURL: "https://twitter.com/naval",
  } as PeopleTypes,
  "Aaron Stupple": {
    name: "Aaron Stupple",
    description:
      "Aaron Stupple is the founder of Conjecture Magazine which applies Critical Rationalism to contemporary issues and the nature of progress. Aaron is an internal medicine physician in Massachusetts.",
    twitterURL: "https://twitter.com/astupple",
  } as PeopleTypes,
  "Logan Chipkin": {
    name: "Logan Chipkin",
    description:
      "Logan Chipkin is a writer based in Philadelphia. His previous publications can be found on his website. He is also working on a fiction novel, chapters of which can be found on his Substack.",
    websiteURL: "http://www.loganchipkin.com/",
    twitterURL: "https://twitter.com/ChipkinLogan",
  } as PeopleTypes,
  "Dennis Hackethal": {
    name: "Dennis Hackethal",
    description:
      "Dennis Hackethal is a philosopher and software engineer. His book A Window on Intelligence is aimed at the general reader and covers artificial general intelligence, the evolution of people, AI safety, and more.",
    websiteURL: "https://blog.dennishackethal.com/",
    twitterURL: "https://twitter.com/dchackethal",
  } as PeopleTypes,
  "Arjun Khemani": {
    name: "Arjun Khemani",
    description:
      "Arjun Khemani is an unconventional high school student who writes about progress, philosophy, science, and optimism and is the host of the Arjun Khemani Podcast.",
    websiteURL: "https://arjunkhemani.com",
    twitterURL: "https://twitter.com/arjunkhemani",
  } as PeopleTypes,
  "Ella Hoeppner": {
    name: "Ella Hoeppner",
    description:
      "Ella Hoeppner is a software engineer with an interest in epistemology, artificial general intelligence, and artificial life. She writes at FourStrands.org and on her website.",
    websiteURL: "https://www.ellahoeppner.com/",
    twitterURL: "https://twitter.com/ella_hoeppner",
  } as PeopleTypes,
  "Bruce Nielson": {
    name: "Bruce Nielson",
    description:
      "Bruce Nielson runs FourStrands.org and hosts the Theory of Anything podcast. Both explore subjects related to David Deutsch's 'Four Strands'.",
    websiteURL: "https://fourstrands.org/",
    twitterURL: "https://twitter.com/bnielson01",
  } as PeopleTypes,
  "Lulie Tanett": {
    name: "Lulie Tanett",
    description:
      "Lulie Tanett is a writer from Oxford, England, specializing in applied Critical Rationalism. She writes about all things epistemology — from education and memetics to productivity and motivation, to how coercion affects rationality, progress and happiness.'",
    websiteURL: "https://reasonisfun.com/",
    twitterURL: "https://twitter.com/reasonisfun",
  } as PeopleTypes,
  "Christofer Lövgren": {
    name: "Christofer Lövgren",
    description: "Christofer Lövgren is running the Do Explain podcast.",
    twitterURL: "https://twitter.com/ReachChristofer",
  } as PeopleTypes,
  "Ben Chugg": {
    name: "Ben Chugg",
    description:
      "Ben is a computer scientist at Stanford Law School, mostly working on sequential decision-making problems. He has done work in optimization, complexity theory, graph theory, and machine learning and is co-host of the Increments podcast.",
    websiteURL: "https://www.incrementspodcast.com/",
    twitterURL: "https://twitter.com/BennyChugg",
  } as PeopleTypes,
  "Vaden Masrani": {
    name: "Vaden Masrani",
    description:
      "Vaden is a Ph.D. student at the University of British Columbia where he focuses on machine learning, probabilistic programming, bayesian inference and other topics. He's also the co-host of the Increments podcast.",
    websiteURL: "https://vmasrani.github.io/",
    twitterURL: "https://twitter.com/VadenMasrani",
  } as PeopleTypes,
  "Stuart Firestein": {
    name: "Stuart Firestein",
    description:
      "Stuart Firestein is a professor of biology at Columbia University. He is the author of Failure: Why Science Is So Successful.",
    websiteURL: "http://stuartfirestein.com/",
  } as PeopleTypes,
  "Aniket Vartak": {
    name: "Aniket Vartak",
    description:
      "Aniket is a Machine Learning researcher, worked at Deep Learning Qualcomm and is currently Chief Scientist at care.ai",
    websiteURL: "http://www.aniketvartak.com/",
    twitterURL: "https://twitter.com/aniketvartak",
  } as PeopleTypes,
  "Daniel C. Elton": {
    name: "Daniel C. Elton",
    description:
      "Daniel C. Elton, Ph. D. worked as a Staff Scientist at the National Institutes of Health and is currently a Data Scientist at Mass General Brigham.",
    websiteURL: "https://moreisdifferent.substack.com/",
    twitterURL: "https://twitter.com/moreisdifferent",
  } as PeopleTypes,
  "Ray Scott Percival": {
    name: "Ray Scott Percival",
    description:
      "Ray Scott Percival holds a Ph.D. from the London School of Economics and founded and edited The Karl Popper Web.",
    websiteURL: "https://www.youtube.com/c/rayscottpercival",
    twitterURL: "https://twitter.com/ray_s_percival",
  } as PeopleTypes,
  "Cam Peters": {
    name: "Cam Peters", // likley Cameron Peters
    description: "Cam Peters writes at falliblepieces.substack.com.",
    twitterURL: "https://twitter.com/campeters4",
    websiteURL: "https://falliblepieces.substack.com/",
  } as PeopleTypes,
  "Oliver Scott Curry": {
    name: "Oliver Scott Curry",
    description:
      "Research Director at kindness.org, Affiliate at Oxford Anthropology, Associate at LSE Philosophy",
    websiteURL: "https://oliverscottcurry.com/",
    twitterURL: "https://twitter.com/oliverscottcurry",
  } as PeopleTypes,
  "Bart Vanderhaegen": {
    name: "Bart Vanderhaegen",
    description:
      "Bart Vanderhaegen runs Fallible management a podcast and consultancy on how to accelerate knowledge growth in organisations.",
    websiteURL: "www.anchor.fm/falliblemanagement",
    twitterURL: "https://twitter.com/B_Vanderhaegen",
  } as PeopleTypes,
  "Jesse Nichols": {
    name: "Jesse Nichols",
    description:
      "Jesse Nichols is a software engineer and worked at Roam Research, Replit and Marble. He writes at infinitedays.org.",
    websiteURL: "https://infinitedays.org/",
    twitterURL: "https://twitter.com/JesseNichols",
  } as PeopleTypes,
  "Phil Filippak": {
    name: "Phil Filippak",
    description:
      "Phil Filippak raises awareness about The Beginning of Infinity wherever he's currently located and publishes occasional essays at unstableorbits.substack.com. He's working on Architect of Thought, a VR ecosystem for experimental brain exercises.",
    websiteURL: "https://unstableorbits.substack.com/",
    twitterURL: "https://twitter.com/blisstweeting",
  } as PeopleTypes,
  "Moritz Wallawitsch": {
    name: "Moritz Wallawitsch",
    description:
      "Moritz Wallawitsch is working on RemNote.com, a knowledge management platform. He writes and podcasts about cognitive augmentation, startups and epistemology at scalingknowledge.substack.com. He also created this website.",
    websiteURL: "https://scalingknowledge.substack.com/",
    twitterURL: "https://twitter.com/moritzw42",
  } as PeopleTypes,
}

// Sources

enum SourceType {
  podcast = "podcast",
  blog = "blog",
}

type Source = {
  name: string
  type: SourceType
  href: string
  authors: (keyof typeof People)[]
}

// Note, if you add an Author here pls make sure you add them to the People object above
export const Sources: Source[] = [
  {
    name: "ToKCast",
    type: SourceType.podcast,
    href: "https://brettroberthall.podbean.com/",
    authors: ["Brett Hall"],
  },
  {
    name: "Conjecture Magazine",
    type: SourceType.blog,
    href: "https://medium.com/conjecture-magazine",
    authors: ["Aaron Stupple"],
  },
  {
    name: "The Four Strands",
    type: SourceType.blog,
    href: "https://fourstrands.org/",
    authors: ["Bruce Nielson"],
  },
  {
    name: "Theory of Anything podcast",
    type: SourceType.podcast,
    href: "https://anchor.fm/four-strands",
    authors: ["Bruce Nielson"],
  },
  {
    name: "Do Explain podcast",
    type: SourceType.podcast,
    href: "https://doexplain.buzzsprout.com/",
    authors: ["Christofer Lövgren"],
  },
  {
    name: "Increments podcast",
    type: SourceType.podcast,
    href: "https://www.incrementspodcast.com/",
    authors: ["Ben Chugg", "Vaden Masrani"],
  },
]
